### ISSUE TITLE
about page code injection

### ISSUE THREAD

**Issue by rhinenoir** [rangzf/vscode-ghost-theme#2]
when you open several tabs, switch between them, the injected codes never run again.
on my blog, I've written several scripts to replace rendered contents of my story, but everytime I switch back to an opened tab, I only get the before-replaced version......

**Comment by rhinenoir** [comment]
hope that everytime I switch between tabs the injected code executed again 



_Sent from my PRO 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Joffey** [comment]
Since not every injected code should be called after tab switched, so I add an API(`window.ghost.history`) to let the injected code do their own logic, you can use this api to listen to the change of url
This api should be called after `ghostcodeReady` event dispatched
Example:
```
document.addEventListener('ghostcodeReady', function() {
  console.log('ghostcode ready')
  window.ghostcode.history.listen((location, action) => {
      // do what you want to do after tab switched
      console.log(location, action)
  })
})
```
You can update ghostcode theme and have a try~

Reference: [History API](https://github.com/ReactTraining/history)

**Comment by rhinenoir** [comment]
@rangzf I've tried several times and now encounter a `weired` bug (or maybe not)

since my scripts are for content replacement, what I expect is:

```
==> press operation occured
==> tab switched, related contents  (e.g. active class you apply to div element there) completely replaced
==> window.ghostcode.history.listen called
```

but seems that now it works like:

```
==> press operation occured
==> window.ghostcode.history.listen called
==> tab switched, related contents  (e.g. active class you apply to div element there) completely replaced
```

as you see ↓

![](https://media.discordapp.net/attachments/420095259125743637/432471637372305408/unknown.png)

url changed, tab not switched, I could only get old content when using `document.getElementByxxx()`…… 

---

btw, actually we know that ghost officially support code injection for a workflow like this:

```
==> markdown content
==> completely rendered html (the content you could get via open api )
==> injected codes execute (generally append to head or footer)
```

If you activate a theme with **no tabs** inside (e.g. default casper), you could only open your story in a new page, then the workflow above triggered again, which means that everytime we `finally` get the content affected by those injected codes

That why I consider code injection important here. I never found bug like this using no-tab-inside themes except another tab-inside theme:joy:.

well, since ghostcode theme is really my style, hope that it could be better maintained O(∩_∩)O~~ thx 

_Sent from my PRO 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Joffey** [comment]
I see ...

Different from casper, ghostcode's post page is a SPA, post changes without whole page refresh, just fetching post data from ajax and then replace the content, so you encountered this problem

```
home page
-> post page // Synchronous rendering of the first article
-> tab click
-> asynchronous fetching post data // need time to wait for data back
-> window.ghostcode.history.listen called // called immediately
-> rerender
```

The new api I added didn't solve your problem is because of `time problem`

`window.ghostcode.history.listen` is invoked immediately after tab clicked, and before content rerended

So, let's change a solution,  I updated ghostcode theme and emit a event `post-refreshed` after new post rendered, and `emitter.on('post-refreshed', () => {})` will solve this problem

So, try this
```
document.addEventListener('ghostcodeReady', function() {
    const yourLogic = function() {
      console.log('post refreshed')
    }
    // immediately call after post rendered synchronously
    yourLogic()
    // listen to 'post-refreshed' event and do what you want
    emitter.on('post-refreshed', yourLogic)
  })
```

**Comment by rhinenoir** [comment]
@rangzf
It works! That's awesome!!!! Many thx to you
![](https://slack-imgs.com/?c=1&url=http%3A%2F%2Fi.giphy.com%2Faxu6dFuca4HKM.gif)

**Comment by Joffey** [comment]
haha~
